base/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',  views.getRoutes),
    path('rooms/', views.getRooms),
    path('rooms/<str:pk>/', views.getRoom),
]

base/urls.py
from django.urls import path
from . import views
# from .views import *

from django.urls import path
from . import views

urlpatterns = [
    # Authentication
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),

    # Home and User Profile
    path('', views.home, name="home"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),
    path('update-user/', views.updateUser, name="update-user"),
    path('ai_playnow/', views.ai_playnow, name="ai_playnow"),
    path('join_room/', views.join_room, name="join_room"),

    # Room Management
    path('room/<str:pk>/', views.room, name="room"),
    path('room_list/', views.room_list, name="room_list"),
    path('create-room/', views.createRoom, name="create-room"),
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('player-list/<int:room_id>/', views.player_list, name='player_list'),
    path('leave-room/', views.leave_room, name='leave_room'),
    path('kick-player/', views.kick_player, name='kick_player'),
    path('check-kickout-status/', views.check_kickout_status, name='check_kickout_status'),

    # Chat Functionality
    path('pong/<str:pk>/', views.pongPage, name="pong"),
    path('chat/new_groupchat/', views.create_groupchat, name="new-groupchat"),
    path('chat/<username>/', views.get_or_create_chatroom, name="start-chat"),
    path('chat/edit/<chatroom_name>/', views.chatroom_edit_view, name="edit-chatroom"),
    path('chat/delete/<chatroom_name>/', views.chatroom_delete_view, name="chatroom-delete"),
    path('chat/leave/<chatroom_name>/', views.chatroom_leave_view, name="chatroom-leave"),
    path('chat/fileupload/<chatroom_name>/', views.chat_file_upload, name="chat-file-upload"),
    path('messages/', views.chat_ui, name="messages"),
    path('messages/<int:id>/', views.chat_group_detail, name='chat_group_detail'),

    # tournament
    path('room/tournament/<str:pk>/', views.tournament_view, name='tournament_view'),
    path('room/<int:pk>/podium/', views.podium_view, name='podium_view'),

    # friends
    path('add_friend/<str:user_id>/', views.add_friend, name='add_friend'),
    path('remove_friend/<str:user_id>/', views.remove_friend, name='remove_friend'),
    path('cancel-friend-request/<int:user_id>/', views.cancel_friend_request, name='cancel_friend_request'),
]

studybud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('base.api.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User, BaseUserManager
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.db import models
import shortuuid
from PIL import Image
import os
import uuid

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)

class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    username = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(unique=True, null=True)
    bio = models.TextField(null=True, default="The User too lazy to add a Bio")
    avatar = models.ImageField(null=True, default="avatar.svg")
    group_chats = models.ManyToManyField('ChatGroup', related_name='group_members', blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    def __str__(self):
        return self.email
    
    def add_friend(self, friend):
        if not Friend.objects.filter(user=self, friend=friend).exists():
            Friend.objects.create(user=self, friend=friend)

    def remove_friend(self, friend):
        try:
            friendship = Friend.objects.get(user=self, friend=friend)
            friendship.delete()
        except Friend.DoesNotExist:
            pass

    def get_friends(self):
        return User.objects.filter(friend_of=self)


class Friend(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='friend_set')
    friend = models.ForeignKey(User, on_delete=models.CASCADE, related_name='related_friend_set')
    confirmed = models.BooleanField(default=False)  # Mutual friendship confirmation
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'friend')
        verbose_name = 'Friendship'
        verbose_name_plural = 'Friendships'

    def __str__(self):
        return f"{self.user.email} - {self.friend.email}"


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    points = models.IntegerField(default=1)
    
    invitation_link = models.CharField(max_length=255, unique=True, blank=True, null=True)

    OPPONENT_TYPE_CHOICES = (
        ('vs Player', 'vs Player'),
        ('Tournament', 'Tournament'),
        ('AI', 'AI'),
    )
    opponent_type = models.CharField(max_length=10, choices=OPPONENT_TYPE_CHOICES, default='AI')

    won_by_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='won_by_user')
    won_by_ai = models.BooleanField(default=False)
    is_expired = models.BooleanField(default=False)
    host_ready = models.BooleanField(default=False)
    opp_ready = models.BooleanField(default=False)
    is_2player = models.BooleanField(default=False)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.invitation_link:
            self.invitation_link = str(uuid.uuid4())
        super().save(*args, **kwargs)


class ChatGroup(models.Model):
    group_name = models.CharField(max_length=128, unique=True, blank=True)
    groupchat_name = models.CharField(max_length=128, null=True, blank=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, null=True, blank=True, default=None)
    admin = models.ForeignKey(User, related_name='groupchats', blank=True, null=True, on_delete=models.SET_NULL)
    users_online = models.ManyToManyField(User, related_name='online_in_groups', blank=True)
    members = models.ManyToManyField(User, related_name='chat_groups', blank=True)
    is_private = models.BooleanField(default=False)
    
    def __str__(self):
        return self.group_name

    def save(self, *args, **kwargs):
        if not self.group_name:
            self.group_name = shortuuid.uuid()
        super().save(*args, **kwargs)
    
    
class GroupMessage(models.Model):
    group = models.ForeignKey(ChatGroup, related_name='chat_messages', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.CharField(max_length=300, blank=True, null=True)
    file = models.FileField(upload_to='files/', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    
    @property
    def filename(self):
        if self.file:
            return os.path.basename(self.file.name)
        else:
            return None
    
    def __str__(self):
        if self.body:
            return f'{self.author.username} : {self.body}'
        elif self.file:
            return f'{self.author.username} : {self.filename}'
    
    class Meta:
        ordering = ['-created']
        
    @property    
    def is_image(self):
        try:
            image = Image.open(self.file) 
            image.verify()
            return True 
        except:
            return False
        

class Match(models.Model):
    player1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='matches_as_player1')
    player2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='matches_as_player2')
    player1_score = models.IntegerField(null=True, blank=True)
    player2_score = models.IntegerField(null=True, blank=True)
    round = models.CharField(max_length=20)
    is_final = models.BooleanField(default=False)
    is_completed = models.BooleanField(default=False)
    winner = models.ForeignKey(User, related_name='match_winner', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.player1} vs {self.player2} - {self.round}"


class Notification(models.Model):
    TYPE_CHOICES = [
        ('friend_request', 'Friend Request'),
        ('friend_request_accepted', 'Friend Request Accepted'),
        # Add more types as needed
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_notifications')
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_notifications', null=True)
    type = models.CharField(max_length=50, choices=TYPE_CHOICES)
    title = models.CharField(max_length=100)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False, db_index=True)
    def __str__(self):
        return f"{self.user.email} - {self.title}"

base/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'bio']

class ChatmessageCreateForm(ModelForm):
    class Meta:
        model = GroupMessage
        fields = ['body']
        widgets = {
            'body' : forms.TextInput(attrs={'placeholder': 'Add message ...', 'class': 'p-4 text-black', 'maxlength' : '300', 'autofocus': True }),
        }
        
        
class NewGroupForm(ModelForm):
    class Meta:
        model = ChatGroup
        fields = ['groupchat_name']
        widgets = {
            'groupchat_name' : forms.TextInput(attrs={
                'placeholder': 'Add name ...', 
                'class': 'p-4 text-black', 
                'maxlength' : '300', 
                'autofocus': True,
                }),
        }
        
        
class ChatRoomEditForm(ModelForm):
    class Meta:
        model = ChatGroup
        fields = ['groupchat_name']
        widgets = {
            'groupchat_name' : forms.TextInput(attrs={
                'class': 'p-4 text-xl font-bold mb-4', 
                'maxlength' : '300', 
                }),
        }


class MatchScoreForm(forms.ModelForm):
    class Meta:
        model = Match
        fields = ['player1_score', 'player2_score']
        widgets = {
            'player1_score': forms.NumberInput(attrs={'min': 0}),
            'player2_score': forms.NumberInput(attrs={'min': 0}),
        }

base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Room
from .serializers import RoomSerializer
from base.api import serializers


@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/rooms/:id'
    ]
    return Response(routes)


@api_view(['GET'])
def getRooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def getRoom(request, pk):
    room = Room.objects.get(id=pk)
    serializer = RoomSerializer(room, many=False)
    return Response(serializer.data)

base/templates/chat/chat.html
<div class="bg-gray-800 w-full h-[4rem] rounded-tr-md rounded-tl-md p-5 text-white">
    {% if home_chat == None %}
        <p>{{room.name}} chat (Live-chat)</p>
    {% else %}
        <p>{{home_chat}} chat (Live-chat)</p>
    {% endif %}
  </div>
  <div  id='chat_container' class="w-full h-[calc(100vh-455px)] bg-indigo-100 p-2 rounded-br-md rounded-bl-md overflow-scroll">

    <ul id='chat_messages' class="flex flex-col justify-end gap-2 p-4">
      {% for message in chat_messages reversed %}
        {% if message.author == user %}
            <!-- Message from Current User -->
            <div class="col-start-6 col-end-13 p-3 rounded-lg">
                <div class="flex items-center justify-start flex-row-reverse">
                    <div class="flex items-center justify-center h-10 w-10 rounded-full bg-indigo-500 flex-shrink-0">
                        {% if message.author.avatar %}
                            <img src="{{ message.author.avatar.url }}" alt="{{ message.author.username }}'s avatar" class="h-full w-full object-cover rounded-full">
                        {% else %}
                            {{ message.author.username|slice:":1" | upper}} <!-- Fallback to displaying the initial letter of username -->
                        {% endif %}
                    </div>
                    <div class="relative mr-3 text-sm bg-indigo-300 py-2 px-4 shadow rounded-xl text-black">
                        <div>{{ message.body }}</div>
                        {% if message.is_seen %}
                            <div class="absolute text-xs bottom-0 right-0 -mb-5 mr-2 text-gray-500">Seen</div>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% else %}
            <!-- Message from Other Users -->
            <div class="col-start-1 col-end-8 p-3 rounded-lg">
                <div class="flex flex-col items-start">
                    <div class="flex flex-row items-center">
                        <div class="flex items-center justify-center h-10 w-10 rounded-full bg-indigo-500 flex-shrink-0 text-black">
                            {% if message.author.avatar %}
                            <a href="{% url 'user-profile' message.author.id %}" class="block h-full w-full rounded-full overflow-hidden">
                                <img src="{{ message.author.avatar.url }}" alt="{{ message.author.username }}'s avatar" class="h-full w-full object-cover">
                            </a>
                            {% else %}
                                {{ message.author.username|slice:":1" | upper}} <!-- Fallback to displaying the initial letter of username -->
                            {% endif %}
                        </div>
                        <div class="relative ml-3 text-sm bg-white py-2 px-4 shadow rounded-xl text-black">
                            <div>{{ message.body }}</div>
                        </div>
                    </div>
                    <!-- Username display below the message content -->
                    <div class="text-xs text-gray-500 mt-1 ml-12">
                        @{{ message.author.username }}
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
  </ul>

   </div>
    <div class="pt-5"></div>
    <form id="chat_message_form" class="w-full"
    hx-ext="ws"
    ws-connect="/ws/chatroom/{{ chatroom_name_ws }}"
    ws-send 
    _="on htmx:wsAfterSend reset() me"
    method="POST">
    {% csrf_token %}
    <div class="w-full pl-3 pr-1 py-1 rounded-3xl border border-gray-400 flex items-center gap-2 justify-between">
      <div class="flex items-center gap-2 flex-1">
        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 22 22" fill="none">
          <g id="User Circle">
            <path id="icon" d="M6.05 17.6C6.05 15.3218 8.26619 13.475 11 13.475C13.7338 13.475 15.95 15.3218 15.95 17.6M13.475 8.525C13.475 9.89191 12.3669 11 11 11C9.6331 11 8.525 9.89191 8.525 8.525C8.525 7.1581 9.6331 6.05 11 6.05C12.3669 6.05 13.475 7.1581 13.475 8.525ZM19.25 11C19.25 15.5563 15.5563 19.25 11 19.25C6.44365 19.25 2.75 15.5563 2.75 11C2.75 6.44365 6.44365 2.75 11 2.75C15.5563 2.75 19.25 6.44365 19.25 11Z" stroke="teal" stroke-width="1.6" />
          </g>
        </svg>
        <input class="flex-1 text-black text-xs font-medium leading-4 focus:outline-none rounded-2xl px-2 py-2" type="text" name="body" maxlength="300" autofocus id="is_body" placeholder="Enter message here...">
      </div>
      <div class="flex items-center gap-2">
        <svg class="cursor-pointer" xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 22 22" fill="none">
          <g id="Attach 01">
            <g id="Vector">
              <path d="M14.9332 7.79175L8.77551 14.323C8.23854 14.8925 7.36794 14.8926 6.83097 14.323C6.294 13.7535 6.294 12.83 6.83097 12.2605L12.9887 5.72925M12.3423 6.41676L13.6387 5.04176C14.7126 3.90267 16.4538 3.90267 17.5277 5.04176C18.6017 6.18085 18.6017 8.02767 17.5277 9.16676L16.2314 10.5418M16.8778 9.85425L10.72 16.3855C9.10912 18.0941 6.49732 18.0941 4.88641 16.3855C3.27549 14.6769 3.27549 11.9066 4.88641 10.198L11.0441 3.66675" stroke="#9CA3AF" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" />
              <path d="M14.9332 7.79175L8.77551 14.323C8.23854 14.8925 7.36794 14.8926 6.83097 14.323C6.294 13.7535 6.294 12.83 6.83097 12.2605L12.9887 5.72925M12.3423 6.41676L13.6387 5.04176C14.7126 3.90267 16.4538 3.90267 17.5277 5.04176C18.6017 6.18085 18.6017 8.02767 17.5277 9.16676L16.2314 10.5418M16.8778 9.85425L10.72 16.3855C9.10912 18.0941 6.49732 18.0941 4.88641 16.3855C3.27549 14.6769 3.27549 11.9066 4.88641 10.198L11.0441 3.66675" stroke="white" stroke-opacity="0.2" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" />
              <path d="M14.9332 7.79175L8.77551 14.323C8.23854 14.8925 7.36794 14.8926 6.83097 14.323C6.294 13.7535 6.294 12.83 6.83097 12.2605L12.9887 5.72925M12.3423 6.41676L13.6387 5.04176C14.7126 3.90267 16.4538 3.90267 17.5277 5.04176C18.6017 6.18085 18.6017 8.02767 17.5277 9.16676L16.2314 10.5418M16.8778 9.85425L10.72 16.3855C9.10912 18.0941 6.49732 18.0941 4.88641 16.3855C3.27549 14.6769 3.27549 11.9066 4.88641 10.198L11.0441 3.66675" stroke="white" stroke-opacity="0.2" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" />
            </g>
          </g>
        </svg>
        <button class="items-center flex px-3 py-2 bg-teal-400 rounded-full shadow">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="none">
            <g id="Send 01">
              <path id="icon" d="M9.04071 6.959L6.54227 9.45744M6.89902 10.0724L7.03391 10.3054C8.31034 12.5102 8.94855 13.6125 9.80584 13.5252C10.6631 13.4379 11.0659 12.2295 11.8715 9.81261L13.0272 6.34566C13.7631 4.13794 14.1311 3.03408 13.5484 2.45139C12.9657 1.8687 11.8618 2.23666 9.65409 2.97257L6.18714 4.12822C3.77029 4.93383 2.56187 5.33664 2.47454 6.19392C2.38721 7.0512 3.48957 7.68941 5.69431 8.96584L5.92731 9.10074C6.23326 9.27786 6.38623 9.36643 6.50978 9.48998C6.63333 9.61352 6.72189 9.7665 6.89902 10.0724Z" stroke="black" stroke-width="1.6" stroke-linecap="round" />
            </g>
          </svg>
          <h3 class="text-black text-xs font-semibold leading-4 px-2">Send</h3>
        </button>
      </div>
    </div>      
</form>

base/templates/chat/chat_message.html
{% if message.author == user %}
<li class="flex justify-end mb-4">
    <div class="bg-green-200 rounded-l-lg rounded-tr-lg p-4 max-w-[75%] text-black">
        <span>{{ message.body }}</span>
    </div>
    <div class="flex items-end">
        <svg height="13" width="8" >
            <path fill="#bbf7d0" d="M6.3,10.4C1.5,8.7,0.9,5.5,0,0.2L0,13l5.2,0C7,13,9.6,11.5,6.3,10.4z"/>
        </svg>
    </div>
</li>
{% else %}
<li>
    <div class="flex justify-start">
        <div class="flex items-end mr-2" >
            <a href="{% url 'user-profile' message.author.id %}">
                <div class="relative">
                    <div id="user-{{ message.author.id }}"></div>
                    <img class="w-8 h-8 rounded-full object-cover" src="{{ message.author.avatar.url }}">
                </div>
            </a>
        </div>
        <div class="flex items-end" >
            <svg height="13" width="8" >
                <path fill="white" d="M2.8,13L8,13L8,0.2C7.1,5.5,6.5,8.7,1.7,10.4C-1.6,11.5,1,13,2.8,13z"></path>
            </svg>
        </div>
        <div class="bg-white p-4 max-w-[75%] rounded-r-lg rounded-tl-lg text-black">
            <span>{{ message.body }}</span>
        </div>  
    </div>
    <div class="text-sm font-light py-1 ml-10">
        <span class="text-white">{{ message.author.profile.name }}</span> 
        <span class="text-gray-400">@{{ message.author.username }}</span>
    </div>
</li>
{% endif %}

base/templates/chat/chatroom_delete.html
{% extends 'layouts/box.html' %}

{% block content %} 

<h1>Delete this chatroom?</h1>

<h2>"{{ chat_group.groupchat_name }}"</h2>

<form method='POST'>
    {% csrf_token %}
    <button type="submit" class="button-red mt-4">Yes, delete</button>
    <a class="button button-gray ml-1" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
</form>

{% endblock %}

base/templates/chat/chatroom_edit.html
{% extends 'layouts/box.html' %}

{% block content %} 

<h1>Edit Chat</h1>

<form method="post">
    {% csrf_token %}
    {{ form }}

    <div class="my-4">
    <h2>Members</h2>
    {% for member in chat_group.members.all %}
    <div class="flex justify-between items-center">
        <div class="flex items-center gap-2 py-2">
            <img class="w-14 h-14 rounded-full object-cover" src="{{ member.profile.avatar }}" />
            <div>
                <span class="font-bold">{{ member.profile.name }}</span> 
                <span class="text-sm font-light text-gray-600">@{{ member.username }}</span>
            </div>
        </div>
        
        {% if member != chat_group.admin %}
        <div class="inline-block pr-4">
            <input type="checkbox" name="remove_members" value="{{ member.id }}" class="relative p-5 cursor-pointer appearance-none rounded-md border after:absolute after:left-0 after:top-0 after:h-full after:w-full after:bg-[url('https://img.icons8.com/ffffff/32/multiply.png')] after:bg-center checked:bg-red-500 hover:ring hover:ring-gray-300 focus:outline-none" />
        </div>
        {% endif %}
    </div> 
    {% endfor %}
    </div>

    <button class="mt-2" type="submit">Update</button>
</form>

<a href="{% url 'chatroom-delete' chat_group.group_name %}" class="flex justify-end mt-4 text-gray-400 hover:text-red-500" >Delete Chatroom</a>

{% endblock %}

base/templates/chat/create_groupchat.html
{% extends 'main.html' %}

{% block content %}

<main class="relative z-10">
  <div class="isolate bg-white px-6 py-10 sm:py-20 lg:px-8">
    <div class="absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[-20rem]" aria-hidden="true">
      <div class="relative left-1/2 -z-10 aspect-[1155/678] w-[36.125rem] max-w-none -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-40rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
    </div>
    <div class="mx-auto max-w-2xl text-center">
      <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Create/Update Chat Group</h2>
    </div>
    <form method="POST"
        method="POST" class="mx-auto mt-10 max-w-xl sm:mt-14">
      {% csrf_token %}
      <div class="grid grid-cols-1 gap-x-8 gap-y-6 sm:grid-cols-2">
        <div class="sm:col-span-2">
          <label for="id_groupchat_name" class="block text-sm font-semibold leading-6 text-black">Groupchat name:</label>
          <div class="mt-2.5">
            <input type="text" name="groupchat_name" placeholder="Add name ..." class="block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset shadow-blue-500 ring-blue-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-blue-400 sm:text-sm sm:leading-6" maxlength="128" autofocus="" id="id_groupchat_name" required="">
          </div>
        </div>
      </div>
      <div class="mt-10 flex space-x-4">
        <a href="{% url 'home' %}" class="btn flex-1 rounded-md bg-cyan-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-green-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Cancel</a>
        <button type="submit" class="flex-1 rounded-md bg-cyan-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-green-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Create</button>
      </div>
    </form>
  </div>
</main>

{% endblock content %}