base/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',  views.getRoutes),
    path('rooms/', views.getRooms),
    path('rooms/<str:pk>/', views.getRoom),
]

base/urls.py
from django.urls import path
from . import views
# from .views import *

from django.urls import path
from . import views

urlpatterns = [
    # Authentication
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),

    # Home and User Profile
    path('', views.home, name="home"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),
    path('update-user/', views.updateUser, name="update-user"),
    path('ai_playnow/', views.ai_playnow, name="ai_playnow"),
    path('join_room/', views.join_room, name="join_room"),

    # Room Management
    path('room/<str:pk>/', views.room, name="room"),
    path('room_list/', views.room_list, name="room_list"),
    path('create-room/', views.createRoom, name="create-room"),
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('player-list/<int:room_id>/', views.player_list, name='player_list'),
    path('leave-room/', views.leave_room, name='leave_room'),
    path('kick-player/', views.kick_player, name='kick_player'),
    path('check-kickout-status/', views.check_kickout_status, name='check_kickout_status'),

    # Chat Functionality
    path('pong/<str:pk>/', views.pongPage, name="pong"),
    path('chat/new_groupchat/', views.create_groupchat, name="new-groupchat"),
    path('chat/<username>/', views.get_or_create_chatroom, name="start-chat"),
    path('chat/edit/<chatroom_name>/', views.chatroom_edit_view, name="edit-chatroom"),
    path('chat/delete/<chatroom_name>/', views.chatroom_delete_view, name="chatroom-delete"),
    path('chat/leave/<chatroom_name>/', views.chatroom_leave_view, name="chatroom-leave"),
    path('chat/fileupload/<chatroom_name>/', views.chat_file_upload, name="chat-file-upload"),
    path('messages/', views.chat_ui, name="messages"),
    path('messages/<int:id>/', views.chat_group_detail, name='chat_group_detail'),

    # tournament
    path('room/tournament/<str:pk>/', views.tournament_view, name='tournament_view'),
    path('room/<int:pk>/podium/', views.podium_view, name='podium_view'),

    # friends
    path('add_friend/<str:user_id>/', views.add_friend, name='add_friend'),
    path('remove_friend/<str:user_id>/', views.remove_friend, name='remove_friend'),
    path('cancel-friend-request/<int:user_id>/', views.cancel_friend_request, name='cancel_friend_request'),
]

studybud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('base.api.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User, BaseUserManager
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.db import models
import shortuuid
from PIL import Image
import os
import uuid

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)

class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    username = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(unique=True, null=True)
    bio = models.TextField(null=True, default="The User too lazy to add a Bio")
    avatar = models.ImageField(null=True, default="avatar.svg")
    group_chats = models.ManyToManyField('ChatGroup', related_name='group_members', blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    def __str__(self):
        return self.email
    
    def add_friend(self, friend):
        if not Friend.objects.filter(user=self, friend=friend).exists():
            Friend.objects.create(user=self, friend=friend)

    def remove_friend(self, friend):
        try:
            friendship = Friend.objects.get(user=self, friend=friend)
            friendship.delete()
        except Friend.DoesNotExist:
            pass

    def get_friends(self):
        return User.objects.filter(friend_of=self)


class Friend(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='friend_set')
    friend = models.ForeignKey(User, on_delete=models.CASCADE, related_name='related_friend_set')
    confirmed = models.BooleanField(default=False)  # Mutual friendship confirmation
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'friend')
        verbose_name = 'Friendship'
        verbose_name_plural = 'Friendships'

    def __str__(self):
        return f"{self.user.email} - {self.friend.email}"


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    points = models.IntegerField(default=1)
    
    invitation_link = models.CharField(max_length=255, unique=True, blank=True, null=True)

    OPPONENT_TYPE_CHOICES = (
        ('vs Player', 'vs Player'),
        ('Tournament', 'Tournament'),
        ('AI', 'AI'),
    )
    opponent_type = models.CharField(max_length=10, choices=OPPONENT_TYPE_CHOICES, default='AI')

    won_by_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='won_by_user')
    won_by_ai = models.BooleanField(default=False)
    is_expired = models.BooleanField(default=False)
    host_ready = models.BooleanField(default=False)
    opp_ready = models.BooleanField(default=False)
    is_2player = models.BooleanField(default=False)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.invitation_link:
            self.invitation_link = str(uuid.uuid4())
        super().save(*args, **kwargs)


class ChatGroup(models.Model):
    group_name = models.CharField(max_length=128, unique=True, blank=True)
    groupchat_name = models.CharField(max_length=128, null=True, blank=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, null=True, blank=True, default=None)
    admin = models.ForeignKey(User, related_name='groupchats', blank=True, null=True, on_delete=models.SET_NULL)
    users_online = models.ManyToManyField(User, related_name='online_in_groups', blank=True)
    members = models.ManyToManyField(User, related_name='chat_groups', blank=True)
    is_private = models.BooleanField(default=False)
    
    def __str__(self):
        return self.group_name

    def save(self, *args, **kwargs):
        if not self.group_name:
            self.group_name = shortuuid.uuid()
        super().save(*args, **kwargs)
    
    
class GroupMessage(models.Model):
    group = models.ForeignKey(ChatGroup, related_name='chat_messages', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.CharField(max_length=300, blank=True, null=True)
    file = models.FileField(upload_to='files/', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    
    @property
    def filename(self):
        if self.file:
            return os.path.basename(self.file.name)
        else:
            return None
    
    def __str__(self):
        if self.body:
            return f'{self.author.username} : {self.body}'
        elif self.file:
            return f'{self.author.username} : {self.filename}'
    
    class Meta:
        ordering = ['-created']
        
    @property    
    def is_image(self):
        try:
            image = Image.open(self.file) 
            image.verify()
            return True 
        except:
            return False
        

class Match(models.Model):
    player1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='matches_as_player1')
    player2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='matches_as_player2')
    player1_score = models.IntegerField(null=True, blank=True)
    player2_score = models.IntegerField(null=True, blank=True)
    round = models.CharField(max_length=20)
    is_final = models.BooleanField(default=False)
    is_completed = models.BooleanField(default=False)
    winner = models.ForeignKey(User, related_name='match_winner', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.player1} vs {self.player2} - {self.round}"


class Notification(models.Model):
    TYPE_CHOICES = [
        ('friend_request', 'Friend Request'),
        ('friend_request_accepted', 'Friend Request Accepted'),
        # Add more types as needed
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_notifications')
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_notifications', null=True)
    type = models.CharField(max_length=50, choices=TYPE_CHOICES)
    title = models.CharField(max_length=100)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False, db_index=True)
    def __str__(self):
        return f"{self.user.email} - {self.title}"

base/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'bio']

class ChatmessageCreateForm(ModelForm):
    class Meta:
        model = GroupMessage
        fields = ['body']
        widgets = {
            'body' : forms.TextInput(attrs={'placeholder': 'Add message ...', 'class': 'p-4 text-black', 'maxlength' : '300', 'autofocus': True }),
        }
        
        
class NewGroupForm(ModelForm):
    class Meta:
        model = ChatGroup
        fields = ['groupchat_name']
        widgets = {
            'groupchat_name' : forms.TextInput(attrs={
                'placeholder': 'Add name ...', 
                'class': 'p-4 text-black', 
                'maxlength' : '300', 
                'autofocus': True,
                }),
        }
        
        
class ChatRoomEditForm(ModelForm):
    class Meta:
        model = ChatGroup
        fields = ['groupchat_name']
        widgets = {
            'groupchat_name' : forms.TextInput(attrs={
                'class': 'p-4 text-xl font-bold mb-4', 
                'maxlength' : '300', 
                }),
        }


class MatchScoreForm(forms.ModelForm):
    class Meta:
        model = Match
        fields = ['player1_score', 'player2_score']
        widgets = {
            'player1_score': forms.NumberInput(attrs={'min': 0}),
            'player2_score': forms.NumberInput(attrs={'min': 0}),
        }

base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Room
from .serializers import RoomSerializer
from base.api import serializers


@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/rooms/:id'
    ]
    return Response(routes)


@api_view(['GET'])
def getRooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def getRoom(request, pk):
    room = Room.objects.get(id=pk)
    serializer = RoomSerializer(room, many=False)
    return Response(serializer.data)

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}
<main class="delete-item layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{{request.META.HTTP_REFERER}}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Back</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" method="POST" action="">
                    {% csrf_token %}
                    <div class="form__group">
                        <p>Are you sure you want to delete "{{obj}}"?</p>
                    </div>

                    <div class="for__group">
                        <input class="btn btn--main" type="submit" value="Confirm" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

base/templates/base/login_register.html
{% extends 'main.html' %}

{% block content %}
<main>

  {% if page == 'login' %}
  <body class="font-inter overflow-hidden">
    <section class="flex justify-center relative">
      <img src="https://pagedone.io/asset/uploads/1702362010.png" alt="gradient background image" class="w-full h-full object-cover fixed">
      <div class="mx-auto max-w-lg px-6 lg:px-8 absolute py-20">
        <img src="https://pagedone.io/asset/uploads/1702362108.png" alt="pagedone logo" class="mx-auto lg:mb-11 mb-8">
        <div class="rounded-2xl bg-white shadow-xl">
          <form action="" class="lg:p-11 p-7 mx-auto" method="POST">
            {% csrf_token %}
            <div class="mb-11">
              <h1 class="text-gray-900 text-center font-manrope text-3xl font-bold leading-10 mb-2">Welcome Back</h1>
              <p class="text-gray-500 text-center text-base font-medium leading-6">ft_transcendence login page</p>
            </div>
            <!-- <input type="text" class="w-full h-12 text-gray-900 placeholder:text-gray-400 text-lg font-normal leading-7 rounded-full border-gray-300 border shadow-sm focus:outline-none px-4 mb-6" placeholder="Username"> -->
            <input id="username" name="email" type="email" class="w-full h-12 text-gray-900 placeholder:text-gray-400 text-lg font-normal leading-7 rounded-full border-gray-300 border shadow-sm focus:outline-none px-4 mb-6" placeholder="email">
            <input id="password" name="password" type="password" class="w-full h-12 text-gray-900 placeholder:text-gray-400 text-lg font-normal leading-7 rounded-full border-gray-300 border shadow-sm focus:outline-none px-4 mb-1" placeholder="Password">
            <a href="javascript:;" class="flex justify-end mb-6">
              <span class="text-indigo-600 text-right text-base font-normal leading-6">Forgot Password?</span>
            </a>
            <button type="submit" class="w-full h-12 text-white text-center text-base font-semibold leading-6 rounded-full hover:bg-indigo-800 transition-all duration-700 bg-indigo-600 shadow-sm mb-11">Login</button>
            <a href="{% url 'register' %}" class="flex justify-center text-gray-900 text-base font-medium leading-6"> Don’t have an account? <span class="text-indigo-600 font-semibold pl-3"> Sign Up</span>
            </a>
          </form>
        </div>
      </div>
    </section>
  </body>
                                            
  {% else %}

  <body class="font-inter overflow-hidden">
    <section class="flex justify-center relative">
      <img src="https://pagedone.io/asset/uploads/1702362010.png" alt="gradient background image" class="w-full h-full object-cover fixed">
      <div class="mx-auto max-w-lg px-6 lg:px-8 absolute py-20">
        <img src="https://pagedone.io/asset/uploads/1702362108.png" alt="pagedone logo" class="mx-auto lg:mb-11 mb-8">
        <div class="rounded-2xl bg-white shadow-xl">
          <form action="" class="lg:p-11 p-7 mx-auto" method="POST">
            {% csrf_token %}
            <div class="mb-11">
              <h1 class="text-gray-900 text-center font-manrope text-3xl font-bold leading-10 mb-2">Register</h1>
              <p class="text-gray-500 text-center text-base font-medium leading-6">ft_transcendence Sign Up page</p>
            </div>
            <input type="text" name="name" maxlength="200" required id="id_name" class="w-full h-12 text-gray-900 placeholder:text-gray-400 text-lg font-normal leading-7 rounded-full border-gray-300 border shadow-sm focus:outline-none px-4 mb-1" placeholder="Your Name">
            <input type="text" name="username" maxlength="200" required id="id_username" class="w-full h-12 text-gray-900 placeholder:text-gray-400 text-lg font-normal leading-7 rounded-full border-gray-300 border shadow-sm focus:outline-none px-4 mb-1" placeholder="Username">
            <input type="email" name="email" maxlength="254" autofocus required id="id_email" class="w-full h-12 text-gray-900 placeholder:text-gray-400 text-lg font-normal leading-7 rounded-full border-gray-300 border shadow-sm focus:outline-none px-4 mb-1" placeholder="email">
            <input type="password" name="password1" autocomplete="new-password" required id="id_password1" class="w-full h-12 text-gray-900 placeholder:text-gray-400 text-lg font-normal leading-7 rounded-full border-gray-300 border shadow-sm focus:outline-none px-4 mb-1" placeholder="Password">
            <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2" class="w-full h-12 text-gray-900 placeholder:text-gray-400 text-lg font-normal leading-7 rounded-full border-gray-300 border shadow-sm focus:outline-none px-4 mb-1" placeholder="Confirm Password">

            <button type="submit" class="w-full h-12 text-white text-center text-base font-semibold leading-6 rounded-full hover:bg-indigo-800 transition-all duration-700 bg-indigo-600 shadow-sm mb-11">Sign Up</button>
            <a href="{% url 'login' %}" class="flex justify-center text-gray-900 text-base font-medium leading-6"> Already have an account? <span class="text-indigo-600 font-semibold pl-3"> Login</span>
            </a>
          </form>
        </div>
      </div>
    </section>
  </body>
  {% endif %}
</main>
{% endblock content %}

base/templates/base/private_messages.html
{% extends 'main.html' %}

{% block content %}

<main>
  <div class="flex flex-row h-[calc(100vh-100px)] antialiased bg-gray-900">
    {% include 'private_message/sidebar.html' %}
    <div class="flex flex-col h-full w-full bg-gray-900 px-4 py-6">
        {% include 'private_message/chat-header.html' %}
        <div class="h-full overflow-hidden py-4">
          <div id="chat_container" class="h-full overflow-y-auto">
              <div id="chat_messages" class="flex flex-col justify-end gap-2 p-4">
                {% include 'private_message/chat-messages.html' %}
              </div>
          </div>
        </div>
        {% include 'private_message/message-input.html' %}
    </div>
  </div>
</main>

{% endblock %}

base/templates/base/room_form.html
{% extends 'main.html' %}

{% block content %}

<main class="relative z-10">
  <div class="isolate bg-white px-6 py-10 sm:py-20 lg:px-8">
    <div class="absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[-20rem]" aria-hidden="true">
      <div class="relative left-1/2 -z-10 aspect-[1155/678] w-[36.125rem] max-w-none -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-40rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
    </div>
    <div class="mx-auto max-w-2xl text-center">
      <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Create/Update Game Room</h2>
    </div>
    <form method="POST"
      hx-target="#room_list_container"
      hx-swap="innerHTML" method="POST" class="mx-auto mt-10 max-w-xl sm:mt-14">
      {% csrf_token %}
      <div class="grid grid-cols-1 gap-x-8 gap-y-6 sm:grid-cols-2">
        <div class="sm:col-span-2">
          <label for="name" class="block text-sm font-semibold leading-6 text-black">Room Name</label>
          <div class="mt-2.5">
            <input type="text" name="name" maxlength="200" required="" id="id_name" class="block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset shadow-blue-500 ring-blue-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-blue-400 sm:text-sm sm:leading-6">
          </div>
        </div>
        <div class="sm:col-span-2">
          <label for="points" class="block text-sm font-semibold leading-6 text-black">Points to Win</label>
          <div class="mt-2.5">
            <input type="number" name="points" value="0" required id="id_points" max="21" min="0" class="block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset shadow-blue-500 ring-blue-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-blue-400 sm:text-sm sm:leading-6">
          </div>
        </div>
        <div class="sm:col-span-2">
          <label for="points" class="block text-sm font-semibold leading-6 text-black">Opponent Type</label>
          <div class="mt-2.5">
            <select id="id_opponent_type" name="opponent_type" class="block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset shadow-blue-500 ring-blue-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-blue-400 sm:text-sm sm:leading-6">
              <option value="vs Player">vs Player</option>
              <option value="Tournament">Tournament</option>
              <!-- <option value="AI">AI</option> -->
            </select>
          </div>
        </div>
        <div class="sm:col-span-2">
          <label for="description" class="block text-sm font-semibold leading-6 text-black">Room Description</label>
          <div class="mt-2.5">
            <textarea name="description" cols="40" rows="10" id="id_description" class="block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"></textarea>
          </div>
        </div>
      </div>
      <div class="mt-10 flex space-x-4">
        <a href="{% url 'home' %}" class="btn flex-1 rounded-md bg-cyan-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-green-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Cancel</a>
        <button type="submit" class="flex-1 rounded-md bg-cyan-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-green-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Create</button>
      </div>
    </form>
  </div>
</main>

{% endblock content %}

base/templates/base/update-user.html
{% extends 'main.html' %}

{% block content %}
<main>
  <div class="bg-white w-full flex flex-col gap-5 px-3 md:px-16 lg:px-28 md:flex-row text-[#161931]">
      <aside class="hidden py-4 md:w-1/3 lg:w-1/4 md:block">
          <div class="sticky flex flex-col gap-2 p-4 text-sm border-r border-indigo-100 top-12">
              <h2 class="pl-3 mb-4 text-2xl font-semibold">Settings</h2>
              <a href="#" class="flex items-center px-3 py-2.5 font-bold bg-white text-indigo-900 border rounded-full">
                  Public Profile
              </a>
              <a href="#"
                 class="flex items-center px-3 py-2.5 font-semibold hover:text-indigo-900 hover:border hover:rounded-full">
                  Account Settings
              </a>
              <a href="#"
                 class="flex items-center px-3 py-2.5 font-semibold hover:text-indigo-900 hover:border hover:rounded-full">
                  Notifications
              </a>
          </div>
      </aside>
      <div class="w-full min-h-screen py-1 md:w-2/3 lg:w-3/4">
          <div class="p-2 md:p-4">
              <div class="w-full px-6 pb-8 mt-8 sm:max-w-xl sm:rounded-lg">
                  <h2 class="pl-6 text-2xl font-bold sm:text-xl">Edit Public Profile</h2>
                  <form class="form" action="" method="POST" enctype="multipart/form-data">
                      {% csrf_token %}
                      <div class="grid max-w-2xl mx-auto mt-8">
                          <div class="flex flex-col items-center space-y-5 sm:flex-row sm:space-y-0">
                              <img class="object-cover w-40 h-40 p-1 rounded-full ring-2 ring-indigo-300 dark:ring-indigo-500"
                                   src="{{user.avatar.url}}" alt="">
                              <div class="flex flex-col space-y-5 sm:ml-8">
                                  <label class="file-input-wrapper py-3.5 px-7 text-base font-medium text-indigo-100 focus:outline-none bg-[#202142] rounded-lg border border-indigo-200 hover:bg-indigo-900 focus:z-10 focus:ring-4 focus:ring-indigo-200">
                                      Change picture
                                      <input type="file" name="avatar" accept="image/*" id="id_avatar" class="hidden">
                                  </label>
                              </div>
                          </div>
                          <div class="items-center mt-8 sm:mt-14 text-[#202142]">
                              <div class="flex flex-col items-center w-full mb-2 space-x-0 space-y-2 sm:flex-row sm:space-x-4 sm:space-y-0 sm:mb-6">
                                  <div class="w-full">
                                      <label for="profile_pic" class="block mb-2 text-sm font-medium text-indigo-900 dark:text-white">Your Name</label>
                                      <input type="text" id="id_name" maxlength="200" name="name" class="bg-indigo-50 border border-indigo-300 text-indigo-900 text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5" placeholder="name" value="{{user.name}}" required>
                                  </div>
                                  <div class="w-full">
                                      <label for="profile_pic" class="block mb-2 text-sm font-medium text-indigo-900 dark:text-white">Your Username</label>
                                      <input type="text" id="id_username" name="username" maxlength="200" class="bg-indigo-300 border border-indigo-300 text-indigo-900 text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5" placeholder="Username" value="{{user.username}}" required readonly>
                                  </div>
                              </div>
                              <div class="mb-2 sm:mb-6">
                                  <label for="profile_pic" class="block mb-2 text-sm font-medium text-indigo-900 dark:text-white">Your email</label>
                                  <input type="email" id="id_email" maxlength="254" name="email" class="bg-indigo-300 border border-indigo-300 text-indigo-900 text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5" placeholder="Email" value="{{user.email}}" required readonly>
                              </div>
                              <div class="mb-6">
                                  <label for="profile_pic" class="block mb-2 text-sm font-medium text-indigo-900 dark:text-white">Bio</label>
                                  <textarea name="bio" cols="40" rows="10" required="" id="id_bio" class="block p-2.5 w-full text-sm text-indigo-900 bg-indigo-50 rounded-lg border border-indigo-300 focus:ring-indigo-500 focus:border-indigo-500" placeholder="Write your bio here..." required>{{user.bio}}</textarea>
                              </div>
                              <div class="flex justify-end">
                                  <button type="submit" class="text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:outline-none focus:ring-indigo-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-indigo-600 dark:hover:bg-indigo-700 dark:focus:ring-indigo-800">Save</button>
                              </div>
                          </div>
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div>
</main>
{% endblock content %}